server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/e-product-service
    username: root
    password: Deep@2009

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      inventoryService:
        maxAttempts: 3
        waitDuration: 2s
#  timelimiter:
#    instances:
#      inventoryService:
#        timeoutDuration: 2s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
